package:
  name: gippy
  version: 1.0.0b8

source:
  # https://github.com/gipit/gippy
  path: ../vendor/gippy
requirements:
  build:
    - gcc
    - python
    - numpy 1.12.0
    - libgdal 2.1.0
    #- swig
    - potrace 1.11
    - wheel

  run:
    - python
    - numpy 1.12.0
    - fiona 1.7.4 
    - jpeg
    - potrace 1.11

build:
  string: py{{py}}_0
  binary_relocation: False

about:
  home: https://github.com/gipit/gippy
  summary: "Gippy is a Python library for image processing of geospatial raster data"
  license: Apache 2.0
